-- ==============================================================================
-- DUMMY DATA SEEDING (FOR TESTING)
-- ==============================================================================

-- 1. Insert Dummy Course
INSERT INTO public.courses (id, title, slug, description, is_published)
VALUES (
    '11111111-1111-1111-1111-111111111111', 
    'Masterclass Digital Marketing F&B', 
    'kelas-kuliner', 
    'Kuasai ekosistem pertumbuhan bisnis F&B secara terstruktur lewat metode Mindset > Skillset > Toolset.', 
    true
) ON CONFLICT DO NOTHING;

-- 2. Insert Dummy Modules
INSERT INTO public.modules (id, course_id, title, order_index)
VALUES 
    ('22222222-2222-2222-2222-222222222221', '11111111-1111-1111-1111-111111111111', 'Modul 1: MINDSET', 1),
    ('22222222-2222-2222-2222-222222222222', '11111111-1111-1111-1111-111111111111', 'Modul 2: SKILLSET', 2),
    ('22222222-2222-2222-2222-222222222223', '11111111-1111-1111-1111-111111111111', 'Modul 3: TOOLSET', 3)
ON CONFLICT DO NOTHING;

-- 3. Insert Dummy Lessons (Using placeholder video IDs, e.g. youtube/vimeo ids)
INSERT INTO public.lessons (id, module_id, title, video_provider, video_id, content_body, order_index, is_preview)
VALUES 
    -- Modul 1
    ('33333333-3333-3333-3333-333333333331', '22222222-2222-2222-2222-222222222221', 'Bab 1: Membangun Mentalitas F&B Owner', 'vimeo', '123456789', '<p>Ini adalah deskripsi bab 1 tentang mindset dasar...</p>', 1, true),
    ('33333333-3333-3333-3333-333333333332', '22222222-2222-2222-2222-222222222221', 'Bab 2: Menghitung Unit Economics & HPP', 'vimeo', '123456789', '<p>Cara menghitung HPP yang benar...</p>', 2, false),
    -- Modul 2
    ('33333333-3333-3333-3333-333333333333', '22222222-2222-2222-2222-222222222222', 'Bab 1: Meta Ads Radius 3-5 KM', 'vimeo', '123456789', '<p>Strategi beriklan lokal...</p>', 1, false),
    -- Modul 3
    ('33333333-3333-3333-3333-333333333334', '22222222-2222-2222-2222-222222222223', 'Bab 1: Template Canva F&B', 'vimeo', '123456789', '<p>Menggunakan template Canva...</p>', 1, false)
ON CONFLICT DO NOTHING;

-- 4. Insert Dummy Attachments
INSERT INTO public.attachments (id, lesson_id, file_name, file_url, file_type)
VALUES 
    ('44444444-4444-4444-4444-444444444441', '33333333-3333-3333-3333-333333333332', 'Kalkulator_HPP.xlsx', 'https://example.com/hpp.xlsx', 'xlsx'),
    ('44444444-4444-4444-4444-444444444442', '33333333-3333-3333-3333-333333333334', 'Prompt_AI_FNB.pdf', 'https://example.com/prompt.pdf', 'pdf')
ON CONFLICT DO NOTHING;


-- ==============================================================================
-- DUMMY USER & ENROLLMENT (For Testing)
-- Note: In a real scenario, users must be created via Supabase Auth API first.
-- You can run this AFTER creating a user manually in the Supabase Dashboard,
-- or just use this for raw data testing. You will need to replace the 'user_id'
-- with the actual UUID generated by Supabase Auth for your test user.
-- ==============================================================================

-- To test RLS, create a user in Supabase Auth via Email/Password (e.g. test@baim.com), 
-- copy their UUID, and run an insert into enrollments like this:
-- 
-- INSERT INTO public.enrollments (user_id, course_id, status, payment_gateway)
-- VALUES ('<YOUR-TEST-USER-UUID>', '11111111-1111-1111-1111-111111111111', 'active', 'manual');
